name: Extract M3U8 URL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  extract-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch and process URL
      run: |
        # Hata ayıklama için curl çıktısını kaydet
        curl -vL -A "Mozilla/5.0" https://sonbahistv5.pages.dev -o response.txt 2> curl-debug.log
        
        # SSL hatası kontrolü
        if [ $? -ne 0 ]; then
          echo "CURL HATASI: SSL/TLS problemi olabilir"
          cat curl-debug.log
          exit 1
        fi

        CONTENT=$(cat response.txt)
        M3U8_URL=$(echo "$CONTENT" | grep -Eo 'https?://[^"'\'']+\.m3u8' | head -1)

        # Debug çıktıları
        echo "Response Length: ${#CONTENT}"
        echo "Extracted URL: $M3U8_URL"
        
        if [ -z "$M3U8_URL" ]; then
          echo "HATA: .m3u8 URL'si bulunamadı! İçerik örneği:"
          head -n 100 response.txt
          exit 1
        fi

        # HTML oluşturma
        echo "<!DOCTYPE html>
        <html>
        <body>
            <a href=\"$M3U8_URL\">$(date +'%Y-%m-%d %H:%M')</a>
        </body>
        </html>" > urls.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add urls.html
        git commit -m "Update: $(date +'%H:%M')" || echo "Değişiklik yok."
        git push
