name: Extract m3u8 URL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download ChromeDriver
        run: |
          # Chrome sürümü ile uyumlu ChromeDriver versiyonunu belirlemek için
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Chrome version: $CHROME_VERSION"
          # Genellikle major versiyon eşleşmesi yeterli olacaktır.
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
          echo "ChromeDriver version: $DRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d .
          chmod +x chromedriver

      - name: Run extraction script
        run: |
          python extract.py

      - name: Upload urls.html as artifact
        uses: actions/upload-artifact@v4
        with:
          name: urls-html
          path: urls.html
