name: Extract M3U8 URL

on:
  workflow_dispatch: # Manuel tetikleme
  schedule:
    - cron: '0 0 * * *' # Her gün UTC 00:00'da çalışır

jobs:
  extract-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch and process URL
      run: |
        # .m3u8 URL'sini çek ve kaydet
        M3U8_URL=$(curl -sL https://sonbahistv5.pages.dev | grep -Eo 'https?://[^"]+\.m3u8' | head -1)
        
        # HTML dosyasını oluştur
        echo "<!DOCTYPE html>
        <html>
        <head>
            <title>M3U8 URLs</title>
        </head>
        <body>
            <pre>$M3U8_URL</pre>
        </body>
        </html>" > urls.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add urls.html
        git commit -m "Update M3U8 URL: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
