name: Update m3u8 URLs

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir çalışacak
  workflow_dispatch:

jobs:
  get_m3u8_url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run m3u8 extraction script
      run: |
        python get_m3u8.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add urls.html
        git commit -m "Update M3U8 URL: $(date +'%Y-%m-%d %H:%M:%S')"
        git push
