name: Extract M3U8 URL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  extract-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch and process URL
      run: |
        # User-agent ekleyerek ve SSL doğrulamasını kapatarak içerik çekme
        CONTENT=$(curl -sL -A "Mozilla/5.0" --ssl-no-revoke https://sonbahistv5.pages.dev)
        
        # Daha kesin regex patterni
        M3U8_URL=$(echo "$CONTENT" | grep -Eo 'https?://[^"'\'']+\.m3u8' | head -1)

        # URL kontrolü
        if [ -z "$M3U8_URL" ]; then
          echo "HATA: .m3u8 URL'si bulunamadı!" > urls.html
          exit 1
        fi

        # HTML oluşturma
        echo "<!DOCTYPE html>
        <html>
        <head>
            <title>M3U8 URLs</title>
            <meta charset=\"UTF-8\">
        </head>
        <body>
            <a href=\"$M3U8_URL\">$M3U8_URL</a>
            <hr>
            <div>Son Güncelleme: $(date +'%Y-%m-%d %H:%M:%S')</div>
        </body>
        </html>" > urls.html

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add urls.html
        git commit -m "Update M3U8 URL: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Değişiklik yok, commit atlanıyor."
        git push
