name: Update m3u8 and Referer URLs

on:
  schedule:
    - cron: "*/5 * * * *" # Her 5 dakikada bir tetikleme
  workflow_dispatch: # Manuel tetikleme için ekleme

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11 # Geçerli bir Python sürümü

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests lxml # Buraya lxml'i ekledik

    - name: Run Python script
      run: python linkupdate.py # script dosyasının adını linkupdate.py olarak değiştirdim

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actionbot@example.com"

    - name: Commit changes
      run: |
        git add .index.html
        git commit -m "Updated m3u8 and referer URLs via GitHub Actions" || echo "No changes to commit"
        git push || echo "No changes to push"
