name: Scrape Blob URL

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir çalışacak
  workflow_dispatch:  # Manuel tetikleme

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
        wget https://chromedriver.storage.googleapis.com/$(echo $CHROME_VERSION | sed 's/\./_/g')/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Python script
      run: |
        python scrape_m3u8.py
