name: Update Referer URL

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_referer_url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests lxml

      - name: Run Python script
        run: |
          python linkupdate.py

      - name: Check git status
        run: git status

      - name: Check changes
        run: git diff .index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actionbot@example.com"
          git add .index.html
          git diff --quiet || git commit -m "Updated referer URL via GitHub Actions"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/myanony1/myApp.git
