name: Update URLs from Redirects

on:
  push:
    branches:
      - main

jobs:
  fetch-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Fetch redirected URL and update urls.html
      run: |
        python urlupdate.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add urls.html
        git commit -m "Updated redirected URL"
        git push origin main
