# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: Domain Değişiklik Kontrolü

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 30 * * * *

jobs:
  DomainKontrol:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name : Depo Kontrolü
        uses : actions/checkout@v4.2.2

      - name : Python 3.11.8 Yükle
        uses : actions/setup-python@v5.3.0
        with :
          python-version: 3.11.8

      - name : Python Sürümünü Göster
        run  : python -c "import sys; print(sys.version)"

      - name : Gereksinimleri Yükle
        run  : |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel

      - name : Betiği Çalıştır
        run  : |
          python update-exotrgoals.py

      - name : Değişiklik Kontrolü
        id   : degisiklik_kontrol
        run  : |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name : Depoyu Güncelle
        if   : steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run  : |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit --author="keyiflerolsun <keyiflerolsun@users.noreply.github.com>" \
            -m "♻️ Domain Değişikliği" -m "💾 Önceki » $GITHUB_SHA"
          git push
