name: Update Referer URL

on:
  schedule:
    # Bu satır 5 dakikada bir çalışmasını sağlar
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalıştırılır
  workflow_dispatch:  # Manuel tetikleme için
  push:
    branches:
      - main  # main branch'ına push yapıldığında da tetiklenebilir

jobs:
  update_referer_url:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Python 3.9 sürümünü kullan

    - name: Install dependencies
      run: |
        pip install requests lxml  # Gerekli kütüphaneleri yükle

    - name: Run Python script
      run: |
        python linkupdate.py  # Python dosyanızı çalıştırın
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token'ı ekle
