name: Update Referer URL

on:
  schedule:
    # Bu satır 5 dakikada bir çalışmasını sağlar
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalıştırılır
  workflow_dispatch:  # manuel tetikleme için
  push:
    branches:
      - main  # main branch'ına push yapıldığında da tetiklenebilir

jobs:
  update_referer_url:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Python 3.9 sürümünü kullan

    - name: Install dependencies
      run: |
        pip install requests lxml  # Gerekli kütüphaneleri yükle

    - name: Run Python script
      run: |
        python linkupdate.py  # Python dosyanızı çalıştırın

    - name: Set up Git credentials
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actionbot@example.com"

    - name: Commit and push changes
      run: |
        git add .index.html  # Değişiklikleri ekle
        git commit -m "Updated referer URL via GitHub Actions" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/myanony1/myApp.git
