name: Update M3U File

on:
  schedule:
    - cron: "0 */3 * * *" # 3 saatte bir çalışır
  workflow_dispatch: # Manuel tetikleme

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kurulum
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: pip install httpx parsel

      - name: M3U Dosyasını Güncelle
        run: python trgoals.py

      - name: Güncellenmiş Dosyayı Commit ve Push Et
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "M3U dosyası güncellendi"
          git push
