name: Update Referer URL and Push

on:
  push:
    branches:
      - main  # Ana dalınıza bağlı olarak değiştirin

jobs:
  update-referer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to update .index.html
        run: |
          python update-url.py  # Python betiğinizin adını buraya yazın

      - name: Commit and Push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .index.html
          git commit -m "Update referer URL in .index.html"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
