name: Fetch Redirected URL

on:
  push:
    branches:
      - main

jobs:
  fetch-url:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx parsel

    - name: Fetch redirected URL
      run: |
        python urlupdate.py

    - name: Check git status
      run: git status

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add urls.html

        # Check if there are changes to commit
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updated redirected URL"
          git push origin main
        fi
