name: Update URLs

on:
  schedule:
    - cron: '*/30 * * * *'  # Bu, her 30 dakikada bir çalışmasını sağlar (UTC'ye göre)
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  update_urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required libraries
        run: |
          pip install requests beautifulsoup4

      - name: Get and update URLs from index.html
        run: |
          python3 update_urls.py

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update URLs in index.html
        run: |
          git add index.html
          git commit -m "Update URLs in index.html"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/myanony1/myApp.git HEAD:main
